name: Build & Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt -y install pkg-config
      - if: matrix.os == 'macos-latest'
        run: brew install pkg-config
      - name: Build
        run: |
          cd evercrypt-rs
          cargo build --verbose --release
      - name: Test evercrypt-sys
        run: |
          cd evercrypt-sys
          cargo test --verbose
      - if: matrix.os == 'ubuntu-latest'
        name: Test evercrypt-rs
        run: |
          cd evercrypt-rs
          cargo test --verbose
      - if: matrix.os == 'ubuntu-latest'
        name: Build & Test 32-bit Linux
        run: |
          cd evercrypt-rs
          cargo test --verbose --features rust-crypto-aes
      - name: Test (rust-crypto-aes)
        run: |
          cd evercrypt-rs
          cargo test --verbose --features rust-crypto-aes
      - name: Test (all-features)
        run: |
          cd evercrypt-rs
          cargo test --verbose --all-features
      - name: Benchmark (rust-crypto-aes)
        run: |
          cd evercrypt-rs
          cargo bench --verbose --features rust-crypto-aes
  fuzz:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-fuzz
          version: latest
      - name: Clean
        run: cargo clean
      - name: Fuzz AEAD
        run: |
          cd evercrypt-rs
          cargo fuzz run aead -- -runs=1000000
      - name: Fuzz ECDH
        run: |
          cd evercrypt-rs
          cargo fuzz run ecdh -- -runs=1000000
